"""rename department

Revision ID: 459c5c2da1b1
Revises: b09b14af8828
Create Date: 2025-09-30 10:37:53.025709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459c5c2da1b1'
down_revision = 'b09b14af8828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
